USE [master]
GO

/****** Object:  Database [Telefon_Rehberi]    Script Date: 06.04.2021 20:53:51 ******/
CREATE DATABASE [Telefon_Rehberi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Telefon_Rehberi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\Telefon_Rehberi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Telefon_Rehberi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\Telefon_Rehberi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Telefon_Rehberi] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Telefon_Rehberi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Telefon_Rehberi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET ARITHABORT OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Telefon_Rehberi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Telefon_Rehberi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Telefon_Rehberi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Telefon_Rehberi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Telefon_Rehberi] SET  MULTI_USER 
GO

ALTER DATABASE [Telefon_Rehberi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Telefon_Rehberi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Telefon_Rehberi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Telefon_Rehberi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Telefon_Rehberi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Telefon_Rehberi] SET QUERY_STORE = OFF
GO

USE [Telefon_Rehberi]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Telefon_Rehberi] SET  READ_WRITE 
GO


